services:
  bot:
    container_name: bot
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - bbb-bot
    depends_on:
      - changeset-server
      - transcription-server

  changeset-server:
    container_name: changeset-server
    restart: always
    build:
      context: https://github.com/bigbluebutton-bot/changeset-grpc.git
      dockerfile: Dockerfile
    networks:
      - bbb-bot
    ports:
      - "5051:5051"

  transcription-server:
    container_name: transcription-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./.models/whisper:/app/models
    tmpfs:
      - /mnt/ramdisk:size=1024m
    env_file:
      - .env
    networks:
      - bbb-bot
    # ports:
    #   - "8001:8001"
    #   - "5000:5000"
    #   - "5001:5001"
    ipc: host
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 1000:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bbb-bot

  translation-server:
    container_name: translation-server
    image: libretranslate/libretranslate:latest-cuda
    restart: unless-stopped
    ports:
      - "8000:5000"
    tty: true
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']     
    command: --ssl --ga-id MY-GA-ID --req-limit 100 --char-limit 500
    volumes:
      - ./.models/libretranslate:/root/.local:rw
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    networks:
      - bbb-bot

networks:
  bbb-bot:
    driver: bridge
