version: '3.9'

services:
  bot:
    container_name: bot
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - bbb-bot
    depends_on:
      - changeset-server
      - transcription-server

  changeset-server:
    container_name: changeset-server
    build:
      context: https://github.com/JulianKropp/Changeset-grpc.git
      dockerfile: Dockerfile
    networks:
      - bbb-bot
    # ports:
    #   - "5051:5051"

  transcription-server:
    container_name: transcription-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./.models:/app/models
    env_file:
      - .env
    networks:
      - bbb-bot
    # ports:
    #   - "8001:8001"
    #   - "5000:5000"
    #   - "5001:5001"
    ipc: host
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]


networks:
  bbb-bot:
    driver: bridge
