version: '3.9'

services:
  bot:
    container_name: bot
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - bbb-bot
    depends_on:
      - changeset-server
      - transcription-server

  changeset-server:
    container_name: changeset-server
    build:
      context: https://github.com/bigbluebutton-bot/changeset-grpc.git
      dockerfile: Dockerfile
    networks:
      - bbb-bot
    # ports:
    #   - "5051:5051"

  transcription-server:
    container_name: transcription-server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./.models:/app/models
    tmpfs:
      - /mnt/ramdisk:size=1024m
    env_file:
      - .env
    networks:
      - bbb-bot
    # ports:
    #   - "8001:8001"
    #   - "5000:5000"
    #   - "5001:5001"
    ipc: host
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 1000:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bbb-bot




networks:
  bbb-bot:
    driver: bridge
